version: '3.8'

services:
  # 1. The Database
  db:
    image: postgres:15-alpine
    container_name: cron-db-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # 2. Redis (THE MISSING PIECE)
  redis:
    image: redis:alpine
    container_name: cron-redis-container
    ports:
      - "6379:6379"

  # 3. The Scheduler
  scheduler:
    build: .
    ports:
    - "8080:8080"
    #container_name: scheduler-node-1
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379  
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  worker:
    build: .
    #No "ports" section! It doesn't need to listen for API requests.
    # It just runs the scheduler loop internally.
    depends_on:
      - db
      - redis
    deploy:
      replicas: 2  

    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: postgres
      # Redis Config
      REDIS_HOST: redis
      REDIS_PORT: 6379

volumes:
  postgres-data: